### ISSUE TITLE
Escaped HTML chars in reference

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/docca#106]
# Description

Some names in the reference include HTML escaped chars instead of the chars in the source code.
 
# Preview

This [example](https://alandefreitas.github.io/boost-utility-docs/utility/ref/boost__operators_lt_T.html) (`,T__gt boost::operators<T, T >`) generated from [this class](https://github.com/alandefreitas/utility/blob/207ecf067dc07af9b23bb63d5354a666681202b7/include/boost/operators_v1.hpp#L880) (`template<class T> struct operators<T, T >`).

# Replicating the issue

```bash
git clone -b docca_ref https://github.com/alandefreitas/utility.git
cd utility/doc
b2
```

File `./html/utility/ref/boost__operators_lt_T.html`

(I'm still coming up with a smaller example to replicate the issue.)

**Comment by evanlenz** [comment]
@alandefreitas Would it be convenient for you to see if this is still an issue?

**Comment by alandefreitas** [comment]
The code on which this was based doesn't exist anymore, but I replicated the code with these classes and the output from docca is ok.

**Comment by evanlenz** [comment]
Oh cool, thanks for checking! I had a feeling it might have been fixed with some more recent changes making replacements more robust. I will close now. (Please correct me if I misunderstood, but it sounds like the issue is obsolete now.)

**Comment by vinniefalco** [comment]
do we have a test?

**Comment by evanlenz** [comment]
I had tried creating one locally (though I don't know if I did it correctly), couldn't reproduce the problem, and then checked back here. I could check it in for review, if you like.

**Comment by vinniefalco** [comment]
Sure if you submit it, @alandefreitas can review it
