### ISSUE TITLE
Question on convenience-header

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/docca#111]
How would I accomplish something like this?
```
  <xsl:template mode="convenience-header" match="@file[contains(., 'boost/url/bnf')]">url/bnf.hpp</xsl:template>
  <xsl:template mode="convenience-header" match="@file[contains(., 'boost/url')]">url.hpp</xsl:template>
  <xsl:template mode="convenience-header" match="@file"/>
```

I am getting "Ambiguous rule match." I want everything in url/bnf to use the bnf.hpp file, and everything else to use url.hpp.

**Comment by evanlenz** [comment]
Add priority=“1” to the first rule. Otherwise they have the same default
priority of 0.5.

**Comment by vinniefalco** [comment]
Yep!!!

**Comment by evanlenz** [comment]
Also, let me know if that doesn’t work and I’ll take a closer look when I’m
near my computer.

**Comment by vinniefalco** [comment]
It works (or else I would not have closed the issue) thanks!!!

**Comment by evanlenz** [comment]
Haha, yes, I emailed before I saw that. Glad to hear it!
