### ISSUE TITLE
sort comparison operators together?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/docca#126]
Is it possible to change how operators are sorted, so that the equality/inequality are sorted together, while the stream operators (`operator<<` and `operator>>`) or the arithmetic operators like plus and minus are kept separate? See:

![image](https://user-images.githubusercontent.com/1503976/183005253-4943c4ca-0566-4b2a-951f-7908fec331fc.png)

**Comment by vinniefalco** [comment]
Do you see the odd man out? lol

**Comment by evanlenz** [comment]
Hmm, this might be an argument for turning off sorting altogether, so the results show up in code (and thus Doxygen) order (which I verified). But that would impact a lot of other pages, and I'm assuming we still generally want to sort member names alphabetically, yes?

**Comment by evanlenz** [comment]
You can see the relevant code for sorting is quite generic: https://github.com/boostorg/docca/blob/develop/include/docca/base-stage1.xsl#L349
