### ISSUE TITLE
Tables?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/docca#133]
Doxygen supports tables:
```
    /** Table example

        First Header  | Second Header
        ------------- | -------------
        Content Cell  | Content Cell
        Content Cell  | Content Cell
    */
```

do we get the information in the XML? I would like to explore this, if it is practical to do so.

**Comment by evanlenz** [comment]
Looks like we get basic information but unfortunately XML is a second-class citizen again here, so colspan, rowspan, and column alignments are not supported. That said, we do get rows and columns and the distinction between a header and non-header cell. I should be able to implement those at least, so the example you posted will work.
