### ISSUE TITLE
Newer versions of doxygen generate different references

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/docca#136]
Doxygen + docca create different ids when doxygen is updated to a version higher than 1.8.15.

Doxygen 1.9.1 generates:

```xml
<name>operator*</name>
```

where docca generates: `url.ref.boost__urls__pct_string_view.operator__star_`.

while doxygen 1.8.5 generates

```xml
<name>operator *</name>
```

where docca generates: `url.ref.boost__urls__pct_string_view.operator___star_`

Reference: https://github.com/boostorg/url/pull/611

**Comment by sdkrystian** [comment]
Fixed in 4b61682742d6fc0d373698d4263502408816006a
