### ISSUE TITLE
boostorg/mysql docs not building

### ISSUE THREAD

**Issue by sdarwin** [boostorg/docca#184]
boostorg/mysql docs are not building on macOS and Windows. Getting the following error.  

```
  File "/Users/runner/work/release-tools/release-tools/github/boostorg/boost/tools/docca/include/docca/quickbook/components.jinja2", line 498, in template
    {%- for part in member.brief -%}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/venvboostdocs/lib/python3.12/site-packages/jinja2/runtime.py", line 417, in __init__
    self._iterator = self._to_iterator(iterable)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/venvboostdocs/lib/python3.12/site-packages/jinja2/runtime.py", line 425, in _to_iterator
    return iter(iterable)
           ^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: '__main__.OverloadSet object' has no attribute 'brief'
```

See https://github.com/sdarwin/release-tools/actions/runs/11525770777/job/32088676007

In the "docs" job, search for: DOCS BUILD FAILED. LIBRARY mysql , and scroll up.

It's possible that a python dependency is missing, or a configuration issue, in which case there is nothing wrong with docca.
Any ideas?

cc: @anarthal

**Comment by anarthal** [comment]
This looks like it's hitting a known docca issue. If that's the case, it should be failing for Linux, too. Can you confirm whether this is the case?

Will look into it in a couple hours anyway.

**Comment by sdarwin** [comment]
> , it should be failing for Linux, too

It's succeeding on Linux.   Also, the main boost releases (on linux) are ok.

**Comment by grisumbras** [comment]
I'll look into this tomorrow. Is it failing on develop or master?

**Comment by anarthal** [comment]
It's hitting this docca issue: https://github.com/boostorg/docca/issues/170

We don't see it in Linux because it doesn't happen with Doxygen 1.9, but it does with Doxygen 1.12.

**Comment by anarthal** [comment]
IIRC the problem can be workarounded by removing the `\relates` commands from the documentation. This is not ideal, but can be an option if fixing this in docca is too complex to be achieved on time for the release. @grisumbras do you think this could be fixed on your side?

**Comment by grisumbras** [comment]
Yeah, I think I can do this in time.
