### ISSUE TITLE
friends show up as derived

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/docca#32]
For example free function `async_connect`, a friend of `timed_stream`, says:

"(Inherited from async_connect)"

**Comment by evanlenz** [comment]
I couldn't find `timed_stream` in the Beast HTML docs (assuming that's where it was originally reported), so I wonder if this one is obsolete too?

**Comment by vinniefalco** [comment]
it was renamed to `basic_stream` before the release:
https://www.boost.org/doc/libs/1_75_0/libs/beast/doc/html/beast/ref/boost__beast__basic_stream.html

**Comment by evanlenz** [comment]
Following up on this. I see async_connect on that basic_stream page, but I don't see it saying "(Inherited from async_connect)". Does that mean this issue is obsolete? Or am I misunderstanding it? Sorry I need the extra handholding!

**Comment by vinniefalco** [comment]
It looks like I got rid of the free functions, so this issue is no longer relevant - good work ;)
