### ISSUE TITLE
private bases should not be displayed

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/docca#34]
Synopsis should not include private bases.

**Comment by vinniefalco** [comment]
```
struct T : private U
{
};
```

**Comment by evanlenz** [comment]
Is this unconditionally true, or should private bases be shown when $include-private-members is enabled?

**Comment by evanlenz** [comment]
The solution I implemented will always suppress the private base from being displayed. I can change it if that's wrong.

**Comment by vinniefalco** [comment]
I think its fine, and since we don't actually use this anywhere important yet - we don't need a definitive answer right now.
