### ISSUE TITLE
Static Members listed as "Members"

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/docca#47]
e.g. `static size-t max_size()` here:
![image](https://user-images.githubusercontent.com/1503976/96346417-96e5c200-1050-11eb-8583-ee3ff83e5b82.png)

**Comment by evanlenz** [comment]
Looks like I can't assign this to myself anymore...

**Comment by vinniefalco** [comment]
Hmm there was a mixup - should work now, sorry!
